### ISSUE TITLE
Decode textures using createImageBitmap, in worker if possible

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/gl#19]
https://aerotwist.com/blog/the-hack-is-back/

**Comment by ydaniv** [comment]
Need help? Got spec?

**Comment by Rich-Harris** [comment]
thank you! i actually ended up implementing this at work today, so I'll close this: https://github.com/sveltejs/gl/blob/661d6908c9c04b2a1608b831ce87df4c314e6daf/scene/Scene.svelte#L110-L127
